name: SSL Certificate Checker

on:
  workflow_dispatch:
    inputs:
      SSL_PROVIDERS:
        description: 'Comma-separated list of providers (aws,azure,gcp,k8s,tf)'
        required: true
        default: 'aws,azure'
  schedule:
    - cron: '0 5 * * 1'
  push:
    branches: [main]

jobs:
  ssl-cert-check:
    runs-on: ubuntu-latest
    env:
      SSL_PROVIDERS: ${{ github.event.inputs.SSL_PROVIDERS || secrets.SSL_PROVIDERS }}

      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCP_REGION: ${{ secrets.GCP_REGION }}

      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
      TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}

      K8S_CONTEXT: ${{ secrets.K8S_CONTEXT }}

      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      JIRA_AUTH_BASIC: ${{ secrets.JIRA_AUTH_BASIC }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Debug Inputs (Optional)
        run: |
          source venv/bin/activate
          python -c 'from config import SSLConfig; print("Providers:", SSLConfig.PROVIDERS); print("Missing:", SSLConfig.validate())'

      - name: Run SSL Cert Checker
        run: |
          source venv/bin/activate
          bash scripts/run_all.sh
